version: "3.1"

services:
  postgres:
    container_name: sgp_db
    restart: always
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sgp_db
